import type { Metadata } from "next";
// Import the CopilotKit Provider
import { CopilotKit } from "@copilotkit/react-core";
// Import Styles
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "CoAgent Powered App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        {/* 
          We wrap the entire app in CopilotKit.
          runtimeUrl: Points to your backend (route.ts)
          agent: The name of the agent defined in your LangGraph/Backend
        */}
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          agent="sample_agent"
          showDevConsole={false}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}